id: P450EEDD2
initial_creation_type: input
source_metadata:
  title: Vajrāyudha
  language: nl
  description: 'Texts by the master Vajrāyudha/Vajraśastra (rdo rje mtshon cha):'
  volume:
    553d673fd7fd4f39b9f7d65adf9ffada:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
created_at: '2022-03-01T02:25:45.898513'
last_modified_at: '2022-03-01T02:25:45.898515'
